동아리 소식 페이지
h-yes-oo/moari pull request #75
Opened 2021-02-07 02:02 UTC by h-yes-oo

- [x] 동아리 소식 페이지 뼈대
- [x] 동아리 상세 페이지 탭마다 라우트

더 해야할 것 !!
- [ ] 동아리 소식 등록하기, 지우기, 수정하기
- [ ] 동아리 소식 사가

2021-02-07 02:13 UTC, zigsong requested changes
오예

2021-02-07 02:13 UTC, zigsong commented on server/index.js
> +const storyRoute = require('./routes/story');
댓

2021-02-07 02:14 UTC, zigsong requested changes
오예

2021-02-08 01:15 UTC, zigsong requested changes
코드 자체는 다 좋아요! 
근데 인덴트 통일한 부분이랑 줄바꿈 더 된 부분 좀 더 다듬으면 될 것 같구
내거 젤 최신 커밋 내용이 여기도 다 들어가 있는 걸 보니 rebase가 아니라 pull을 한 건가? 
그렇다면 당근을 흔들어 주세요(?)
rebase를 해야 커밋이 깔끔하게 분리가 됨! (아마도) 

이 이후에도 커밋할 거 하나 남은 거 같은데 (카톡으로 말한거)
내가 마킹한 부분들 수정하고 하려면 `git reset`이나 `git rebase`로 지금 이 커밋에 수정 내용들 합친 다음 깔끔하게 커밋할 수 있음! 
잘 모르겠으면 구냥 다음 커밋에 합쳐서 ㄱㄱ

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +    try{
```suggestion
    try {
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +            if( err) return res.status(400).json({ success: false, err})
```suggestion
            if (err) return res.status(400).json({ success: false, err})
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +        for(let i = 0; i < list.length; i++) {
```suggestion
        for (let i = 0; i < list.length; i++) {
```
for문도 ( 전에 한 칸 띄우기!

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +        for(const comment of comments) {
```suggestion
        for (const comment of comments) {
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +            if (comment.responseTo){
```suggestion
            if (comment.responseTo) {
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +                for(const answer of otherAnswers){
```suggestion
                for (const answer of otherAnswers){
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +                    if (!includes(result,answer)){
```suggestion
                    if (!includes(result,answer)) {
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +                for(const answer of answers) {
```suggestion
                for (const answer of answers) {
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/comment.js
> +    } catch(err){
```suggestion
    } catch(err) {
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/story.js
> +        if(err) return res.json({ success: false, err })
```suggestion
        if (err) return res.json({ success: false, err })
```

2021-02-08 01:15 UTC, zigsong commented on server/routes/story.js
> +        if(err) return res.json({ success: false, err })
```suggestion
        if (err) return res.json({ success: false, err })
```

2021-02-08 01:15 UTC, zigsong commented on src/components/pages/ClubDetailPage/index.tsx
> +                    <CommentList user={user} clubId={club._id}/>
`ClubDetailPage`의 세부 페이지들이니까 
컴포넌트 이름들을 `ClubDetail`로 시작하게 하면 어떨까? 
`ClubDetailComments` 이런 식으로? 
전체 큰 그림에서 봤을 때 `CommentList`라고 하면 어디 뭘 가리키는지 헷갈릴 수 있으니까!

2021-02-08 01:15 UTC, zigsong commented on src/components/templates/ClubIntro/index.tsx
> +
줄바꿈이 한 번 더 들어갔어여

2021-02-08 01:15 UTC, zigsong commented on src/components/templates/StoryList/index.tsx
> +
줄바꿈 한 줄 빼기

2021-02-08 09:16 UTC, h-yes-oo commented on src/components/pages/ClubDetailPage/index.tsx
> +                    <CommentList user={user} clubId={club._id}/>
좋아좋아🙆🏻‍♀️

2021-02-08 09:17 UTC, merged